---
- name: Resize SAP LUNs
  hosts: "{{ sap_hosts_group | default('sap') }}"
  serial: 1
  gather_facts: false
  tasks:
    - name: Include Role convert_lun_serial
      ansible.builtin.include_role:
        name: convert_lun_serial

