---
- name: Set sap_hosts_group based on the input
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize sap_hosts_group
      ansible.builtin.set_fact:
        sap_hosts_group: []

    - name: Set sap_hosts_group based on location
      ansible.builtin.set_fact:
        sap_hosts_group: "{{ sap_hosts_group + [item] }}"
      with_items: "{{ groups['sap'] }}"
      when:
        - location is not defined or location == 'sap' or location == 'both' or location == hostvars[item].city

- name: Execute a script on the AIX jump host
  hosts: aix_jumphost
  gather_facts: false
  tasks:
    - name: Execute the get WWN command
      ansible.builtin.raw: "{{ get_wwn_cmd }}"
      register: wwns
      when: initiators is not defined

    - name: Show initiators (must be a comma separeted list)
      ansible.builtin.debug:
        msg: "{{ wwns.stdout_lines }}"
      when: initiators is not defined

    - name: Set initiators variable
      ansible.builtin.set_fact:
        stored_wwns: "{{ initiators if initiators is defined else wwns.stdout_lines }}"

- name: Create Add Initiator to igroup fcp_{{ aix_host }}_01
  hosts: "{{ hostvars['localhost']['sap_hosts_group'] }}"
  serial: 1
  gather_facts: false
  tasks:
    - name: Include role igroup initiator
      ansible.builtin.include_role:
        name: sgs.ontap.igroup
        tasks_from: initiator.yml
      vars:
        state: "{{ state | default('present') }}"
        vserver: "{{ vserver_sap_fc }}"
        initiator_group: "fcp_{{ aix_host }}_01"
        names: "{{ hostvars[groups['aix_jumphost'][0]]['stored_wwns'] }}"
