---
- name: Set sap_hosts_group based on the input
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Initialize sap_hosts_group
      ansible.builtin.set_fact:
        sap_hosts_group: []

    - name: Set sap_hosts_group based on location
      ansible.builtin.set_fact:
        sap_hosts_group: "{{ sap_hosts_group + [item] }}"
      with_items: "{{ groups['sap'] }}"
      when:
        - location is defined
        - location == 'sap' or location == hostvars[item].city

    - name: Show group
      ansible.builtin.debug:
        msg: "sap_hosts_group is set to {{ sap_hosts_group }}"
