---
- name: Set sap_hosts_group based on the input
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set sap_hosts_group variable
      ansible.builtin.set_fact:
        sap_hosts_group: >-
          {{ 'sap' if location == 'sap' else
             item if location == hostvars.city else '' }}
      with_items: "{{ groups['sap'] }}"
      when: location is defined
      
    - name: Show group
      debug:
        msg: "sap_hosts_group is set to {{ sap_hosts_group }}"
