---
- name: Set sap_hosts_group based on the input
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set sap_hosts_group variable
      ansible.builtin.set_fact:
        sap_hosts_group: >-
          {{ 'sap' if location == 'sap' else
             item if location == hostvars[item].city else '' }}
      with_items: "{{ groups['sap'] }}"
      when: location is defined
      
- name: Create SAP HANA Volumes, Qtrees, and LUNs
  hosts: "{{ hostvars['localhost']['sap_hosts_group'] }}"
  serial: 1
  gather_facts: false
  tasks:
    - name: Show sap_hosts_group
      ansible.builtin.debug:
        msg: "sap_hosts_group is set to {{ sap_hosts_group }}"
