---
- name: Set sap_hosts_group based on the input
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Define sap_hosts_group
      ansible.builtin.set_fact:
        sap_hosts_group: "{{ groups['sap'] if location is not defined or location == 'sap' else groups['sap'] | selectattr('cluster_name', 'equalto', location) | list }}"

    - name: Show group
      ansible.builtin.debug:
        msg: "sap_hosts_group is set to {{ sap_hosts_group }}"
