---
delete_volume_05: false
delete_volume_06: false
# For testing only
ontap_validate_certs: false
netapp_username: admin
netapp_password: Netapp1!
aix_host: server308
source_server: server308
destination_server: server309
