---
execute_refresh_prepare_aix_command: true
execute_refresh_complete_aix_command: true
execute_nseries_removal_check_aix_command: true
volume_sap_clone:
  - source_name: "gdc_fcp_sap_{{ source_server }}_05"
    destination_name: "gdc_fcp_sap_{{ destination_server }}_05_clone"
  - source_name: "gdc_fcp_sap_{{ source_server }}_06"
    destination_name: "gdc_fcp_sap_{{ destination_server }}_06_clone"
sap_hana:
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_02"
      size_gb: 387
      qtrees:
        - name: "{{ sap_sid }}_hanashared"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sapbin_20.lun"
              lun_id: 20
              size_gb: 256
        - name: "{{ sap_sid }}_sapbin"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sapbin_21.lun"
              lun_id: 21
              size_gb: 20
    - name: "gdc_fcp_sap_{{ aix_host }}_04"
      size_gb: "{{ hanalog_size_gb | float * 4 * 1.4 }}"
      qtrees:
        - name: "{{sap_sid }}_hanalog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_40.lun"
              os_type: linux
              lun_id: 40
              size_gb: "{{ hanalog_size_gb }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_41.lun"
              os_type: linux
              lun_id: 41
              size_gb: "{{ hanalog_size_gb }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_42.lun"
              os_type: linux
              lun_id: 42
              size_gb: "{{ hanalog_size_gb }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_43.lun"
              os_type: linux
              lun_id: 43
              size_gb: "{{ hanalog_size_gb }}"
    - name: "gdc_fcp_sap_{{ aix_host }}_05"
      size_gb: "{{ hanadata_size_gb | float * 4 * 1.4 }}"
      qtrees:
        - name: "{{sap_sid }}_hanadata"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_50.lun"
              os_type: linux
              lun_id: 50
              size_gb: "{{ hanadata_size_gb }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_51.lun"
              os_type: linux
              lun_id: 51
              size_gb: "{{ hanadata_size_gb }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_52.lun"
              os_type: linux
              lun_id: 52
              size_gb: "{{ hanadata_size_gb }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_53.lun"
              os_type: linux
              lun_id: 53
              size_gb: "{{ hanadata_size_gb }}"
usr_sap: 0
usr_sap_daa: 0
usr_sap_sid: 0
sapmnt_sid: 0
apoopt: 0
db2_db2sid: 0
db2_sid: 0
db2dump: 0
db2_log: 0
db2_dir: 0
db2_data1: 0
db2_data2: 0
db2_data3: 0
db2_data4: 0
db2_arc: 0
lca_poopt: 2
lc_root: 4
lc_sdbbin: 2
lc_sdbdata: 10
lc_saplog: 2
lc_arclog: 2
lc_bkup: 10
sap_bin_size: "{{ usr_sap | int + usr_sap_daa | float + usr_sap_sid | float + sapmnt_sid | float + apoopt | float }}"
sap_db2_bin_size: "{{ db2_db2sid | float + db2_sid | float + db2dump | float }}"
sap_db2_data_size: "{{ db2_dir | float + db2_data1 | float + db2_data2 | float + db2_data3 | float + db2_data4 | float}}"
sap_lc_db_size: "{{ lc_sdbbin + lc_root + lc_bkup + lc_saplog + lc_arclog + lc_sdbdata }}"
sap_bin:
  name: bin
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_02"
      size_gb: "{{ (sap_bin_size | float + sap_db2_bin_size | float + 7 * 0.25) * 1.4 }}"
      qtrees:
        - name: "{{ sap_sid }}_sapbin"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sapbin_21.lun"
              lun_id: 21
              size_gb: "{{ sap_bin_size | float + 4 * 0.25 }}"
sap_db2_bin:
  name: db2_bin
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_02"
      size_gb: "{{ (sap_bin_size | float + sap_db2_bin_size | float + 7 * 0.25) * 1.4 }}"
      qtrees:
        - name: "{{ sap_sid }}_db2"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2_20.lun"
              lun_id: 20
              size_gb: "{{ sap_db2_bin_size | float + 4 * 0.25 }}"
sap_log:
  name: log
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_05"
      size_gb: "{{ (db2_log | float + 7 * 0.25) * 1.4 }}"
      qtrees:
        - name: "{{ sap_sid }}_db2log"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2log_50.lun"
              lun_id: 50
              size_gb: "{{ db2_log | float + 4 * 0.25 }}"
sap_data:
  name: data
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_06"
      size_gb: "{{ (sap_db2_data_size | float + 7 * 0.25) * 1.4 }}"
      qtrees:
        - name: "{{ sap_sid }}_db2data"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_60.lun"
              lun_id: 21
              size_gb: "{{ db2_dir | float + db2_data1 | float + 4 * 0.25 }}"
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_61.lun"
              lun_id: 61
              size_gb: "{{ db2_data2 | float + 4 * 0.25 }}"
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_62.lun"
              lun_id: 62
              size_gb: "{{ db2_data2 | float + 4 * 0.25 }}"
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_63.lun"
              lun_id: 63
              size_gb: "{{ db2_data2 | float + 4 * 0.25 }}"
sap_archlog:
  mame: archlog
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_07"
      size_gb: "{{ (db2_arc | float + 7 * 0.25) * 1.4 }}"
      qtrees:
        - name: "{{ sap_sid }}_db2arclog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2arclog_70.lun"
              lun_id: 70
              size_gb: "{{ db2_arc | float + 4 * 0.25 }}"
sap_lc_db:
  name: lc_db
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_08"
      size_gb: "{{ (sap_lc_db_size | float + 7 * 0.25) * 1.4 }}"
      qtrees:
        - name: "{{ sap_sid }}_sdb"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdb_80.lun"
              lun_id: 80
              size_gb: "{{ lc_root | float + lc_sdbbin | float + lc_bkup | float + 4 * 0.25 }}"
        - name: "{{ sap_sid }}_sdblog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdblog_81.lun"
              lun_id: 81
              size_gb: "{{ lc_saplog | float + 4 * 0.25 }}"
        - name: "{{ sap_sid }}_sdbarclog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdbarclog_82.lun"
              lun_id: 82
              size_gb: "{{ lc_arclog | float + 4 * 0.25 }}"
        - name: "{{ sap_sid }}_sdbdata"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdbdata_83.lun"
              lun_id: 83
              size_gb: "{{ lc_arclog | float + 4 * 0.25 }}"
sap_environment:
  db:
    - "{{ sap_bin }}"
    - "{{ sap_db2_bin }}"
    - "{{ sap_log }}"
    - "{{ sap_data }}"
    - "{{ sap_archlog }}"
  ci:
    - "{{ sap_bin }}"
  cilc:
    - "{{sap_bin }}"
    - "{{sap_lc_db }}"
  cidb:
    - "{{ sap_bin }}"
    - "{{ sap_db2_bin }}"
    - "{{ sap_log }}"
    - "{{ sap_data }}"
    - "{{ sap_archlog }}"
  cidblc:
    - "{{ sap_bin }}"
    - "{{ sap_db2_bin }}"
    - "{{ sap_log }}"
    - "{{ sap_data }}"
    - "{{ sap_archlog }}"
    - "{{ sap_lc_db }}"
  lc:
    - "{{ sap_lc_db }}"
