---
execute_refresh_prepare_aix_command: true
execute_refresh_complete_aix_command: true
execute_nseries_removal_check_aix_command: true
sap_sid: "{{ sid | lower }}"
volume_factor: 1.4
# SECTION - SAP REFRESH
volume_sap_clone:
  - source_name: "gdc_fcp_sap_{{ source_server }}_05"
    destination_name: "gdc_fcp_sap_{{ destination_server }}_05_clone"
  - source_name: "gdc_fcp_sap_{{ source_server }}_06"
    destination_name: "gdc_fcp_sap_{{ destination_server }}_06_clone"
# SECTION - CREATE SAP HANA LUNS
sap_hana:
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_02"
      size_gb: 386
      qtrees:
        - name: "{{ sap_sid }}_hanashared"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_hanashared_20.lun"
              os_type: linux
              lun_id: 20
              size_gb: 256
        - name: "{{ sap_sid }}_sapbin"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sapbin_21.lun"
              os_type: linux
              lun_id: 21
              size_gb: 20
    - name: "gdc_fcp_sap_{{ aix_host }}_04"
      size_gb: "{{ hanalog_size | int * 4 * 1.4 }}"
      qtrees:
        - name: "{{sap_sid }}_hanalog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_40.lun"
              os_type: linux
              lun_id: 40
              size_gb: "{{ hanalog_size }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_41.lun"
              os_type: linux
              lun_id: 41
              size_gb: "{{ hanalog_size }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_42.lun"
              os_type: linux
              lun_id: 42
              size_gb: "{{ hanalog_size }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanalog_43.lun"
              os_type: linux
              lun_id: 43
              size_gb: "{{ hanalog_size }}"
    - name: "gdc_fcp_sap_{{ aix_host }}_05"
      size_gb: "{{ hanadata_size | int * 4 * 1.4 }}"
      qtrees:
        - name: "{{sap_sid }}_hanadata"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_50.lun"
              os_type: linux
              lun_id: 50
              size_gb: "{{ hanadata_size }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_51.lun"
              os_type: linux
              lun_id: 51
              size_gb: "{{ hanadata_size }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_52.lun"
              os_type: linux
              lun_id: 52
              size_gb: "{{ hanadata_size }}"
            - name: "{{aix_host}}_{{ sap_sid }}_hanadata_53.lun"
              os_type: linux
              lun_id: 53
              size_gb: "{{ hanadata_size }}"
# SECTION - CREATE SAP LUNS
usr_sap_size: 0
usr_sap_daa_size: 0
usr_sap_sid_size: 0
sapmnt_sid_size: 0
apoopt_size: 0
db2_db2sid_size: 0
db2_sid_size: 0
db2dump_size: 0
db2_log_size: 0
db2_dir_size: 0
db2_data1_size: 0
db2_data2_size: 0
db2_data3_size: 0
db2_data4_size: 0
db2_arc_size: 0
poopt_size: 0
lc_root_size: 4
lc_sdbbin_size: 2
lc_sdbdata_size: 10
lc_saplog_size: 2
lc_arclog_size: 2
lc_bkup_size: 10
sap_environment:
  db:
    - "{{ sap_bin }}"
    - "{{ sap_db2_bin }}"
    - "{{ sap_log }}"
    - "{{ sap_data }}"
    - "{{ sap_archlog }}"
  ci:
    - "{{ sap_bin }}"
  cilc:
    - "{{sap_bin }}"
    - "{{sap_lc_db }}"
  cidb:
    - "{{ sap_bin }}"
    - "{{ sap_db2_bin }}"
    - "{{ sap_log }}"
    - "{{ sap_data }}"
    - "{{ sap_archlog }}"
  cidblc:
    - "{{ sap_bin }}"
    - "{{ sap_db2_bin }}"
    - "{{ sap_log }}"
    - "{{ sap_data }}"
    - "{{ sap_archlog }}"
    - "{{ sap_lc_db }}"
  lc:
    - "{{ sap_lc_db }}"
sap_bin_size: "{{ usr_sap_size | int + usr_sap_daa_size | int + usr_sap_sid_size | int + sapmnt_sid_size | int + apoopt_size | int }}"
sap_db2_bin_size: "{{ db2_db2sid_size | int + db2_sid_size | int + db2dump_size | int }}"
sap_db2_data_size: "{{ db2_dir_size | int + db2_data1_size | int + db2_data2_size | int + db2_data3_size | int + db2_data4_size | int }}"
sap_lc_db_size: "{{ lc_sdbbin_size | int + lc_root_size | int + lc_bkup_size | int + lc_saplog_size + | int lc_arclog_size + | int lc_sdbdata_size | int }}"
sap_bin:
  name: bin
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_02"
      size_gb: "{{ (sap_bin_size | int * volume_factor | float) | int }}" 
      qtrees:
        - name: "{{ sap_sid }}_sapbin"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sapbin_21.lun"
              os_type: linux
              lun_id: 21
              size_gb: "{{ sap_bin_size }}"
sap_db2_bin:
  name: db2_bin
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_02"
      size_gb: "{{ (sap_bin_size | int + sap_db2_bin_size | int * volume_factor | float) | int }}"
      qtrees:
        - name: "{{ sap_sid }}_db2"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2_20.lun"
              os_type: linux
              lun_id: 20
              size_gb: "{{ sap_db2_bin_size }}"
sap_log:
  name: log
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_05"
      size_gb: "{{ (db2_log | int * volume_factor | float) | int }}"
      qtrees:
        - name: "{{ sap_sid }}_db2log"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2log_50.lun"
              os_type: linux
              lun_id: 50
              size_gb: "{{ db2_log_size }}"
sap_data:
  name: data
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_06"
      size_gb: "{{ (sap_db2_data_size | int * volume_factor | float) | int }}"
      qtrees:
        - name: "{{ sap_sid }}_db2data"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_60.lun"
              os_type: linux
              lun_id: 21
              size_gb: "{{ db2_dir_size | int + db2_data1_size | int }}"
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_61.lun"
              os_type: linux
              lun_id: 61
              size_gb: "{{ db2_data2_size | int }}"
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_62.lun"
              os_type: linux
              lun_id: 62
              size_gb: "{{ db2_data3_size | int }}"
            - name: "{{aix_host}}_{{ sap_sid }}_db2data_63.lun"
              os_type: linux
              lun_id: 63
              size_gb: "{{ db2_data4_size | int }}"
sap_archlog:
  mame: archlog
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_07"
      size_gb: "{{ (db2_arc_size | int * volume_factor | float) | int }}"
      qtrees:
        - name: "{{ sap_sid }}_db2arclog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_db2arclog_70.lun"
              os_type: linux
              lun_id: 70
              size_gb: "{{ db2_arc_size | int }}"
sap_lc_db:
  name: lc_db
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_08"
      size_gb: "{{ (sap_lc_db_size | int }}"
      qtrees:
        - name: "{{ sap_sid }}_sdb"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdb_80.lun"
              os_type: linux
              lun_id: 80
              size_gb: "{{ lc_root_size | int + lc_sdbbin_size | int + lc_bkup_size | int }}"
        - name: "{{ sap_sid }}_sdblog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdblog_81.lun"
              os_type: linux
              lun_id: 81
              size_gb: "{{ lc_saplog_size }}"
        - name: "{{ sap_sid }}_sdbarclog"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdbarclog_82.lun"
              os_type: linux
              lun_id: 82
              size_gb: "{{ lc_arclog_size | int }}"
        - name: "{{ sap_sid }}_sdbdata"
          luns:
            - name: "{{aix_host}}_{{ sap_sid }}_sdbdata_83.lun"
              os_type: linux
              lun_id: 83
              size_gb: "{{ lc_sdbdata_size | int }}"
# SECTION - CREATE SAP OS LUNS
sap_os:
  name: os
  volumes:
    - name: "gdc_fcp_sap_{{ aix_host }}_01"
      size_gb: "{{ (rootvg_size * volume_factor | float) | int }}"
      qtrees:
        - name: rootvg
          luns:
            - name: "{{aix_host}}_rootvg_10.lun"
              lun_id: 10
              size_gb: "{{ rootvg_size }}"
    - name: "gdc_fcp_sap_{{ aix_host }}_03"
      size_gb: "{{ (swapvg_size * volume_factor | float) | int }}"
      qtrees:
        - name: swapvg
          luns:
            - name: "{{aix_host}}_swapvg_30.lun"
              lun_id: 30
              size_gb: "{{ swapvg_size }}"
