---
all:
  hosts:
    local:
      ansible_connection: local
      ansible_hostname: 127.0.0.1
  children:
    sap:
      hosts:
        cluster1:
        cluster2:
    exch:
      hosts:
        GDCNTAP31:
        GDCNTAP32:
    fss:
      hosts:
        GDCNTAP41:
        GDCNTAP42:
    fss_leg:
      hosts:
        GDCNTAP51:
        GDCNTAP52:
    fss_dr:
      hosts:
        GDCNTAP44:
    lab:
      hosts:
        GDCNTAP99:
    san_backup:
      hosts:
        GDCNTAP03:
    nas_backup:
      hosts:
        GDCNTAP43:
    aix_jumphost:
      hosts:
        GDC00620:
